---
title: "Titanic Survival Rate"
author: "David Sierra Perez"
date: "`r Sys.Date()`"
output: word_document
---


### **Problem**
* What were the highest chances of survival rate on the Titanic based on Passenger Class, Age and Sex?
* Is age also the factor affecting the titanic survival rate?
* What is the possible survival rate of a 20 year old man?

### **What is being tried to accomplish from this project?**
The purpose of this project is to learn the basics of machine learning. We will look at data from a case competition in Kaggle. The competition is using data from the Titanic to predict survival rates during the titanic. We will use different data mining techniques to find patterns in the data.

### **Introduction**
One of the biggest shipwrecks ever recorded was the Titanic. On April 15, 1912, the Titanic that has been said to be “Unsinkable” sank after colliding with an iceberg. To make things worse, the ship was not equipped with enough lifeboats for the passengers and crew members. As a result, over 1500 people died during the incident. Since the Titanic happened in the 1900s. One can assume that women and kids were given priority to get on the lift boats. In this project we will dig deeper into this and try to find out if any other factors played a role in the people who survived. For instance, if passenger class was a factor and age as well. 

### **Dataset**
The dataset being used is from Kaggle.com. It contains information from passenger id, if they survived, ticket class, sex, age, number of siblings, number of parents, ticket number, passenger fare, cabin number and lastly port of embark. Kaggle came with 2 data sets. The train data set that tells us whether the passenger survived or died. Survival is given with the value of 1. Did not survive was given with the value of 0. In this project, we will only look at Survived, Pclass (passenger class), Sex, and Age for the the data mining.

### **Literature Survey (existing work on this dataset)** 
The Titanic competition has existed for a couple of years now. There have been more than thousands of projects relating to the ship. A lot of work has been done on this dataset. Also, there are currently over 14,000 teams competing in the Kaggle competition. The data we retrieved from Kaggle is more specific and simple. We found out  most of the work being done on this dataset has a detailed statistical analysis along with machine learning model implementation. But, the data were more focused on the passenger class and the gender or has related to different predictors like family, cabin number, age and more. However, we limited the predictors to passenger class, gender, and age as we believe that it was an important factor for our project in knowing what age range possibly survived the most. We gathered the data which was pre-processed and specifically analyzed the data based on the passenger class, age and gender.

### **Analysis & Results**
Our first step is to load libraries and upload the data into R.
```{R Loading Data}
#install.packages("tidyverse")
#install.packages("readr")
#install.packages("ggplot2")
#install.packages("dplyr")
#install.packages("janitor")
#install.packages("skimr")
#install.packages("here")

library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
library(janitor)
library(skimr)
library(here)

train <- read_csv("Dataset/train.csv")
```

Lets look at the first 6 rows of data for train dataset

```{R Head}
head(train)
```

Next we will looks at a summary of the data provided

```{R Skim_without_charts}
skim_without_charts(train)
```

From the Summary found using "skim_without_charts()" we noticed a couple of things
* There is 891 observations (rows)
* There are 12 columns
* 5 columns are string/character variables
* 7 columns are integers
* we have missing values for Cabin, Embarked and Age. 

### **Cleaning Data**
Our analysis is based on the following columns:
* PasssengerId
* Survived
* Pclass
* Age
* Sex

The other columns we will drop.
```{R drop columns & save to csv for Tableau}

write.csv(train, "train_clean.csv", row.names=FALSE)
keep_columns = c("PassengerId", "Survived", "Pclass", "Age", "Sex")

cleaned_train <- train[keep_columns]

skim_without_charts(cleaned_train)

```

```{R Drop remaining Na}
cleaned_train <- cleaned_train %>% 
  drop_na()
```


Before we can do further analysis, we need to convert Sex into a boolean variable. To do this i am choosing to name the following genders with the following number.
 * Male = 1
 * Female = 0

```{R clean2}
cleaned_train$Sex[cleaned_train$Sex == "male"] <- 1      
cleaned_train$Sex[cleaned_train$Sex == "female"] <- 0  

head(cleaned_train)
```

### **Now we will do a quick analysis of our data**
The first step of our analysis was to get a general count of Sex, Passenger Class, Age, and whether someone survived from the train data.

We start of with SEX.

```{R Barplot Gender}
ggplot(cleaned_train, aes(x = Sex))+ 
  geom_bar(fill = "steelblue") + 
  labs("text", title = "Total Count of Each Gender") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.5, color = "white") +
  theme_classic()
```


Here is a graph for Passenger Class.

```{R Barplot Pclass}
ggplot(cleaned_train, aes(x = Pclass))+ 
  geom_bar(fill = "steelblue") + 
  labs("text", title = "Total Count for Each Passenger Class") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.5, color = "white") +
  theme_classic()
```
```{R Barplot Age}
ggplot(cleaned_train, aes(x=Age)) + 
  geom_histogram(binwidth=1, fill = "steelblue" ) + 
  labs("text", title = "Distribution of Age") +
  theme_classic()
```


```{R Barplot Survived}
ggplot(cleaned_train, aes(x = Survived))+ 
  geom_bar(fill = "steelblue") + 
  labs("text", title = "Total Count of Each Gender", subtitle = "0 = Did not Survive | 1 = Survived") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 5.5, color = "white") +
  theme_classic()
```

A couple points from the first 4 graphs:
* There are more males than females in the dataset
* There are more passngers in class 3
* A majority of people are in the ages between 15 to 45
* More people died than survived

## **Next lets see even more Analysis**


```{R Barplot S/F}
ggplot(cleaned_train, aes(x = Survived, fill = Sex))+ 
 geom_bar() + 
  geom_text(aes(label = ..count..), stat = "count", hjust = 1, vjust = 1.5, color = "white", position = "stack")+
  labs("text", title = "Survivability by Gender", subtitle = "0 = Did not Survive | 1 = Survived")
```


## **Decision Tree**
We will see try to predict the survival rate of the passenger by Sex, Age, and Passenger Class. Lets take a look at our data again. 



```{R cleaaan}
cleaned_train
```

Lets look at a decision tree.


```{R Decision Tree}
#install.packages("tree")
library(tree)
dec_tree <- tree(Survived ~ Sex + Pclass + Age, data = cleaned_train)

print(dec_tree)
```
```{R summary_tree}
plot(dec_tree)
text(dec_tree, pretty = 1)
#female is 0
#male is 1
```


```{R hh}
logistic_1 <- glm(Survived ~ Sex + Pclass + Age, family = 'binomial', data = cleaned_train)

summary(logistic_1)
```

```{R}
cleaned_train$Survival_Rate <- predict(logistic_1, newdata = cleaned_train, type = "response")
cleaned_train
```

```{R}
cleaned_train <- cleaned_train %>% mutate(L_Survived = ifelse(Survival_Rate > .50, 1,0))

head(cleaned_train)
```
### **Problem & Answer**
* What were the highest chances of survival rate on the Titanic based on Passenger Class, Age and Sex?
    * Based on our analysis, the survival rate was the highest for the first passenger class, the youngest peple
      and people who were females.
    
* Is age also the factor affecting the titanic survival rate?
    * Yes age is a main factor in the titanic. Those who were younger were most likely to survive.
    
* What is the possible survival rate of a 20 year old man in the first passenger class?
    * Based on our decision tree, the survival rate of a 20 year old man in 1st class is aproximately 45.4%.
    
    
## **Check out the link below for Tableau charts**
Click [Here!](https://public.tableau.com/app/profile/david.sierra.perez8682/viz/Titanic_16897474016460/PercentSurvivedBasedonPassengerClass#1)
